### PR TITLE
Add music "Abitti Litty" by Folkboy

### PR DESCRIPTION
**Pull request by ahnl**
Added "Abitti Litty" by Folkboy to the music selection. This will ensure that there will be something for every students' music taste. Some students may prefer modern and energetic music like this over the other current choices.

The license is CC BY 3.0.

https://soundcloud.com/testausserveri/folkboy-abitti-litty

image

### CODE REVIEW

**Comment by faitti** [comment]
In my opinion this is extremely necessary update because it's 2022 and equality in everything is a standard nowadays. Also I and many others don't really listen mainstream genres such as Pop/Rap/Rock etc. So it would be amazing to have at least one song per genre in Abitti.

**Comment by mplattu** [comment]
This is perhaps the first time we've been *listening* a PR in the product owner team meeting. Thanks for this experience!

As you probably have figured out the background muzak is meant to mask the noise caused by the other test takers. According to the feedback there are candidates who play attached videos in a loop if there are a music track. First we thought adding just the white noise track but finally decided to add some more similarly neutral pieces. 

Since every music track increases the size of the disk image we don't have any plans for improving our music offerings atm. This is the case regardless of the inspiring, relentless beauty of the pieces of music on the offer.

I hope your career in entertainment business will skyrocket in a similar way as in IT security. Again, thanks for the beat!

**Comment by raikasdev** [comment]
YTL today
abitti litty

**Comment by developerfromjokela** [comment]
image

**Pull request closed without merging**
